# Generated by Django 2.2.28 on 2024-09-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_standing', models.BooleanField(default=True)),
                ('winner', models.BooleanField(default=False)),
                ('out_gw', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='?', max_length=1)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Gameweek')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='?', max_length=1)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Gameweek')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team')),
            ],
        ),
    ]
