# Generated by Django 2.2.28 on 2024-09-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='out_gw',
        ),
    ]
