# Generated by Django 2.2.28 on 2024-09-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_remove_player_out_gw'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='week_lost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
