# Generated by Django 2.2.28 on 2024-09-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_team_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='hidden',
        ),
    ]
