# Generated by Django 2.2.28 on 2024-10-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_auto_20241008_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastManStanding',
            new_name='Winner',
        ),
    ]
