# Generated by Django 2.2.28 on 2024-10-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_auto_20241008_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
