# Generated by Django 2.2.28 on 2024-10-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_delete_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='weeks_to_ignore',
            field=models.BooleanField(default=False),
        ),
    ]
